apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  labels:
    app: url-shortener
data:
  database_host: "postgres"
  database_port: "5432"
  database_user: "urluser"
  database_name: "urldb"
  redis_host: "redis"
  redis_port: "6379"
