apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

resources:
  # Namespaces (Lab 6.1)
  - namespaces.yaml
  # Core application resources
  - deployment.yaml
  - service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - ingress.yaml
  - analytics-cronjob.yaml
  - cleanup-cronjob.yaml

secretGenerator:
  - name: postgres-secret
    literals:
      - password=urlshortenerpassword123

commonLabels:
  managed-by: argocd
