apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml

secretGenerator:
  - name: postgres-secret
    literals:
      - password=urlshortenerpassword123

commonLabels:
  app: url-shortener
  managed-by: argocd
